      INCLUDE 'k_gB1.f'
      INCLUDE 'k_gB2.f'
      INCLUDE 'k_gB3.f'
      INCLUDE 'k_gB4.f'
      INCLUDE 'k_gB5.f'
      INCLUDE 'k_gB6.f'
      INCLUDE 'k_gB7.f'
      INCLUDE 'k_gB8.f'
      INCLUDE 'k_gB9.f'
      INCLUDE 'k_gB10.f'
      INCLUDE 'k_gB11.f'
      INCLUDE 'k_gB12.f'
      INCLUDE 'k_gB13.f'
      INCLUDE 'k_gB14.f'
      INCLUDE 'k_gB15.f'
      INCLUDE 'k_gB16.f'
      
